import { env } from 'cloudflare:workers';
import { describe, expect, it } from 'vitest';
import { createArtist, createCollection, createGenre, createLabel, createSong, createTapeDraft, saveTape } from '../../src/lib/services/catalog';
import { deleteCatalogEntity } from '../../src/lib/services/catalog-delete';

describe('catalog deletion', () => {
  it('restricts linked entities and recalculates visibility after deleting a tape', async () => {
    const userId = crypto.randomUUID();
    const now = Date.now();
    await env.DB.prepare('INSERT INTO user (id, name, email, emailVerified, createdAt, updatedAt) VALUES (?, ?, ?, 1, ?, ?)').bind(userId, 'ผู้ลบ', `${userId}@example.com`, now, now).run();
    const suffix = userId.slice(0, 8);
    const artist = await createArtist(env.DB, userId, `ศิลปินลบ${suffix}`);
    const label = await createLabel(env.DB, userId, `ค่ายลบ${suffix}`);
    const genre = await createGenre(env.DB, `แนวลบ${suffix}`);
    const song = await createSong(env.DB, userId, { title: `เพลงลบ${suffix}`, artistIds: [artist.id] });
    const tape = await createTapeDraft(env.DB, userId, `เทปลบ${suffix}`);
    const imageId = crypto.randomUUID();
    const fullKey = `tapes/${tape.id}/${imageId}-full.webp`;
    const thumbKey = `tapes/${tape.id}/${imageId}-thumb.webp`;
    await env.BUCKET.put(fullKey, new Uint8Array([1, 2]));
    await env.BUCKET.put(thumbKey, new Uint8Array([3, 4]));
    await env.DB.prepare("INSERT INTO tape_image (id, tapeId, kind, fullKey, thumbKey, width, height, bytes, position) VALUES (?, ?, 'front', ?, ?, 100, 100, 4, 0)").bind(imageId, tape.id, fullKey, thumbKey).run();
    await env.DB.prepare('UPDATE site_stats SET imageBytes = imageBytes + 4 WHERE id = 1').run();
    await saveTape(env.DB, userId, { id: tape.id, title: `เทปลบ${suffix}`, releaseType: 'album', artistIds: [artist.id], labelId: label.id, genreIds: [genre.id], tracks: [{ songId: song.id, side: 'A', position: 1 }], status: 'published' });
    const noop = () => {};
    await expect(deleteCatalogEntity(env.DB, env.BUCKET, 'tapes', tape.id, 'ผิดชื่อ', noop)).rejects.toThrow('พิมพ์ชื่อเทป');
    await expect(deleteCatalogEntity(env.DB, env.BUCKET, 'songs', song.id, undefined, noop)).rejects.toThrow('ยังอยู่ในเทป');
    await expect(deleteCatalogEntity(env.DB, env.BUCKET, 'artists', artist.id, undefined, noop)).rejects.toThrow('ยังผูก');
    const pending: Promise<unknown>[] = [];
    await deleteCatalogEntity(env.DB, env.BUCKET, 'tapes', tape.id, `เทปลบ${suffix}`, promise => pending.push(promise));
    await Promise.all(pending);
    expect(await env.BUCKET.head(fullKey)).toBeNull();
    expect((await env.DB.prepare('SELECT publishedTapeCount FROM song WHERE id = ?').bind(song.id).first<{ publishedTapeCount: number }>())?.publishedTapeCount).toBe(0);
    expect((await env.DB.prepare('SELECT publishedTapeCount FROM artist WHERE id = ?').bind(artist.id).first<{ publishedTapeCount: number }>())?.publishedTapeCount).toBe(0);
    const stats = await env.DB.prepare('SELECT tapeCount, publishedTapeCount, imageBytes FROM site_stats WHERE id = 1').first<{ tapeCount: number; publishedTapeCount: number; imageBytes: number }>();
    expect(stats?.tapeCount).toBe(0);
    expect(stats?.publishedTapeCount).toBe(0);
    expect(stats?.imageBytes).toBe(0);
    await deleteCatalogEntity(env.DB, env.BUCKET, 'songs', song.id, undefined, noop);
    await deleteCatalogEntity(env.DB, env.BUCKET, 'artists', artist.id, undefined, noop);
    await deleteCatalogEntity(env.DB, env.BUCKET, 'labels', label.id, undefined, noop);
    await deleteCatalogEntity(env.DB, env.BUCKET, 'genres', genre.id, undefined, noop);
    const collection = await createCollection(env.DB, userId, `คอลเล็กชัน${suffix}`);
    await deleteCatalogEntity(env.DB, env.BUCKET, 'collections', collection.id, undefined, noop);
  });
});
